pimcore_studio_backend:
    data_object_data_adapter_mapping:
        Torq\PimcoreHelpersBundle\DataObject\Data\Adapter\ArrayFieldAdapter:
            - "arrayField"
        Torq\PimcoreHelpersBundle\DataObject\Data\Adapter\HashedInputAdapter:
            - "arrayField"
