services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Torq\PimcoreHelpersBundle\Attribute\:
      resource: '../src/Attribute'
      public: true

    Torq\PimcoreHelpersBundle\Command\:
      resource: '../src/Command'
      public: true

    Torq\PimcoreHelpersBundle\Service\:
        resource: '../src/Service'
        public: true

    Torq\PimcoreHelpersBundle\Repository\:
        resource: '../src/Repository'
        public: true

    Torq\PimcoreHelpersBundle\Webpack\:
        resource: '../src/Webpack'
        public: true

    pimcore.data_object.grid_column_config.operator.factory.classification_store_key_getter:
        class: Pimcore\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: Torq\PimcoreHelpersBundle\GridColumnConfig\Operator\ClassificationStoreKeyGetter
        tags:
            - { name: pimcore.data_object.grid_column_config.operator_factory, id: ClassificationStoreKeyGetter }
