services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Torq\PimcoreHelpersBundle\Service\:
        resource: '../src/Service'
        public: true

    Torq\PimcoreHelpersBundle\Repository\:
        resource: '../src/Repository'
        public: true

    pimcore.data_object.grid_column_config.operator.factory.classification_store_key_getter:
        class: Pimcore\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: Torq\PimcoreHelpersBundle\GridColumnConfig\Operator\ClassificationStoreKeyGetter
        tags:
            - { name: pimcore.data_object.grid_column_config.operator_factory, id: ClassificationStoreKeyGetter }

# add more services, or override services that need manual wiring
#    Torq\PimcoreHelpersBundle\ExampleClass:
#        arguments:
#            - "@service_id"
#            - "plain_value"
#            - "%parameter%"
