services:
    _defaults:
        autowire: true
        autoconfigure: true

    Torq\PimcoreHelpersBundle\Service\Adapter\ArrayFieldAdapter:
        tags:
            - { name: 'pimcore.studio_backend.data_adapter' }
    Torq\PimcoreHelpersBundle\Grid\Column\Definition\DataObject\ArrayFieldDefinition: ~
    Torq\PimcoreHelpersBundle\Grid\Column\Definition\DataObject\HashedInputDefinition: ~
    Torq\PimcoreHelpersBundle\Grid\Column\Resolver\DataObject\ArrayFieldResolver: ~
    Torq\PimcoreHelpersBundle\Grid\Column\Resolver\DataObject\HashedInputResolver: ~
