services:
    Torq\PimcoreHelpersBundle\Grid\Column\Definition\DataObject\ArrayFieldDefinition: ~
    Torq\PimcoreHelpersBundle\Grid\Column\Definition\DataObject\HashedInputDefinition: ~
    Torq\PimcoreHelpersBundle\Grid\Column\Resolver\DataObject\ArrayFieldResolver: ~
    Torq\PimcoreHelpersBundle\Grid\Column\Resolver\DataObject\HashedInputResolver: ~
