name: "Frontend Build"

on:
  push:
    paths:
      - "studio/**"
  pull_request:
    paths:
      - "studio/**"
  workflow_dispatch:

concurrency:
  group: frontend-build-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  frontend-build:
    permissions:
      contents: write
    uses: pimcore/workflows-collection-public/.github/workflows/reusable-studio-frontend-build.yaml@6c65230251c7a706661340d7f72bc23f882ea16a # main
    with:
      working-directory: ./studio
      node-version: "26"
      build-output-path: ./public/build/production/
